### ISSUE TITLE
When project build: package org.springframework.context.support does not exist

### ISSUE THREAD

**Issue by dino10bit** [calipho-sib/nextprot-api#29]
Hello, I cloned nextprot-api ropo.
Java version: adopt-openj9-1.8
In intellij, when I run "Build project", returned:

/Users/bob/projects/nextprot-api/tasks/src/main/java/org/nextprot/api/tasks/PopulateRDBMSWithQueriesApp.java:3:43
java: package org.springframework.context.support does not exist

How to build **nextprot-api** ?
Which Java version are you using?

**Comment by pamichel** [comment]
Hi Dino,
Sorry to respond so late we're very busy.
I have updated the README.md in root dir. You must use mvn to install everything, i.e
`$> mvn clean compile install -DskipTests`
But you will need to create postgres databases for it wo work properly.
And some other services are required in many use cases (solr, SPARQL end-point and pepx services)

**Comment by pamichel** [comment]
We are still compiling with java 8.
If you need more information please feel free to contact us again.
Hope this helps.
